name: 'tui'
version: 0.0.1
homepage: https://github.com/damoti/tui
description: >
  Text-based User Interface components for building console application.
author: Lex Berezhny <lex@damoti.com>
dev_dependencies:
  path: any
  unittest: any
